stages:
  preprocess:
    cmd: python src/data_prep.py
    deps:
    - data/raw/dataset.csv
    - src/data_prep.py
    outs:
    - data/processed
  train:
    cmd: python src/train.py --train data/processed/train.csv --test data/processed/test.csv
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models

